import Head from "next/head";
import React from "react";
import Nav from "../Nav";
import SearchBar from "../SearchBar";

export default function MainLayout({ children }) {
  return (
    <main>
      <Head>
        <title>Travel Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/vite.svg" />
      </Head>
      <Nav />
      <SearchBar />
      {children}
    </main>
  );
}
