export const data = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/rfnmMYuZ6EKOBvQLp2wqP21v7sI.jpg",
      id: 774752,
      title: "The Guardians of the Galaxy Holiday Special",
      original_language: "en",
      original_title: "The Guardians of the Galaxy Holiday Special",
      overview:
        "On a mission to make Christmas unforgettable for Quill, the Guardians head to Earth in search of the perfect present.",
      poster_path: "/8dqXyslZ2hv49Oiob9UjlGSHSTR.jpg",
      media_type: "movie",
      genre_ids: [35, 878, 12],
      popularity: 539.588,
      release_date: "2022-11-25",
      video: false,
      vote_average: 7.527,
      vote_count: 391,
    },
    {
      adult: false,
      backdrop_path: "/9DpB6wC1iY5jxLz91RT8tIIsXaf.jpg",
      id: 119051,
      name: "Wednesday",
      original_language: "en",
      original_name: "Wednesday",
      overview:
        "Wednesday Addams is sent to Nevermore Academy, a bizarre boarding school where she attempts to master her psychic powers, stop a monstrous killing spree of the town citizens, and solve the supernatural mystery that affected her family 25 years ago — all while navigating her new relationships.",
      poster_path: "/jeGtaMwGxPmQN5xM4ClnwPQcNQz.jpg",
      media_type: "tv",
      genre_ids: [10765, 9648, 35],
      popularity: 1956.231,
      first_air_date: "2022-11-23",
      vote_average: 8.802,
      vote_count: 969,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/93SxdkiR3gBcbG5FxIt0DCBttul.jpg",
      id: 111837,
      name: "Willow",
      original_language: "en",
      original_name: "Willow",
      overview:
        "Many years after the events of the original film, legendary sorcerer Willow leads a group of misfit heroes on a dangerous rescue mission through a world beyond their wildest imaginations.",
      poster_path: "/jhdSPDlhswjN1r6O0pGP3ZvQgU8.jpg",
      media_type: "tv",
      genre_ids: [10765, 10759, 18],
      popularity: 72.701,
      first_air_date: "2022-11-30",
      vote_average: 7.4,
      vote_count: 8,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/bQXAqRx2Fgc46uCVWgoPz5L5Dtr.jpg",
      id: 436270,
      title: "Black Adam",
      original_language: "en",
      original_title: "Black Adam",
      overview:
        "Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.",
      poster_path: "/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg",
      media_type: "movie",
      genre_ids: [28, 14, 878],
      popularity: 13251.998,
      release_date: "2022-10-19",
      video: false,
      vote_average: 7.284,
      vote_count: 2169,
    },
    {
      adult: false,
      backdrop_path: "/pHCLEj9i1R929p8feiwyq2arSgi.jpg",
      id: 873126,
      title: "My Name Is Vendetta",
      original_language: "it",
      original_title: "Il mio nome è vendetta",
      overview:
        "After old enemies kill his family, a former mafia enforcer and his feisty daughter flee to Milan, where they hide out while plotting their revenge.",
      poster_path: "/2cHGGU1CAhECNx6YY3oEbo6ysYb.jpg",
      media_type: "movie",
      genre_ids: [28, 12, 80, 9648, 53],
      popularity: 26.513,
      release_date: "2022-11-30",
      video: false,
      vote_average: 6.0,
      vote_count: 3,
    },
    {
      adult: false,
      backdrop_path: "/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg",
      id: 505642,
      title: "Black Panther: Wakanda Forever",
      original_language: "en",
      original_title: "Black Panther: Wakanda Forever",
      overview:
        "Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death. As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.",
      poster_path: "/ps2oKfhY6DL3alynlSqY97gHSsg.jpg",
      media_type: "movie",
      genre_ids: [28, 12, 878],
      popularity: 1960.335,
      release_date: "2022-11-09",
      video: false,
      vote_average: 7.5,
      vote_count: 1093,
    },
    {
      adult: false,
      backdrop_path: "/kumeuomlQwwi8RPTFUXjVoit91o.jpg",
      id: 945897,
      title: "A Man of Action",
      original_language: "es",
      original_title: "Un hombre de acción",
      overview:
        "Loosely inspired by the life of Lucio Urtubia, explore the figure of the so-called anarchist 'Robin Hood,' who ran a legendary counterfeiting operation in Paris that put him in the crosshairs of America's largest bank, when he managed to obtain a huge amount of money by forging traveler's checks to invest in causes he believed in.",
      poster_path: "/2sZAwJI7hPIXwQKp95RFXhCm619.jpg",
      media_type: "movie",
      genre_ids: [18, 36],
      popularity: 26.417,
      release_date: "2022-11-30",
      video: false,
      vote_average: 7.7,
      vote_count: 3,
    },
    {
      adult: false,
      backdrop_path: "/c1bz69r0v065TGFA5nqBiKzPDys.jpg",
      id: 830784,
      title: "Lyle, Lyle, Crocodile",
      original_language: "en",
      original_title: "Lyle, Lyle, Crocodile",
      overview:
        "When the Primm family moves to New York City, their young son Josh struggles to adapt to his new school and new friends. All of that changes when he discovers Lyle — a singing crocodile who loves baths, caviar and great music — living in the attic of his new home. But when Lyle’s existence is threatened by evil neighbor Mr. Grumps, the Primms must band together to show the world that family can come from the most unexpected places.",
      poster_path: "/irIS5Tn3TXjNi1R9BpWvGAN4CZ1.jpg",
      media_type: "movie",
      genre_ids: [35, 10751, 10402],
      popularity: 2159.911,
      release_date: "2022-10-07",
      video: false,
      vote_average: 7.71,
      vote_count: 88,
    },
    {
      adult: false,
      backdrop_path: "/198vrF8k7mfQ4FjDJsBmdQcaiyq.jpg",
      id: 76600,
      title: "Avatar: The Way of Water",
      original_language: "en",
      original_title: "Avatar: The Way of Water",
      overview:
        "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
      poster_path: "/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
      media_type: "movie",
      genre_ids: [878, 28, 12],
      popularity: 622.981,
      release_date: "2022-12-14",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/s1xnjbOIQtwGObPnydTebp74G2c.jpg",
      id: 90669,
      name: "1899",
      original_language: "zh",
      original_name: "1899",
      overview:
        "Passengers on an immigrant ship traveling to the new continent get caught in a mysterious riddle when they find a second vessel adrift on the open sea.",
      poster_path: "/8KGvYHQNOamON6ufQGjyhkiVn1V.jpg",
      media_type: "tv",
      genre_ids: [9648, 18],
      popularity: 2067.956,
      first_air_date: "2022-11-17",
      vote_average: 7.914,
      vote_count: 349,
      origin_country: ["DE"],
    },
    {
      adult: false,
      backdrop_path: "/ajztm40qDPqMONaSJhQ2PaNe2Xd.jpg",
      id: 83867,
      name: "Star Wars: Andor",
      original_language: "en",
      original_name: "Star Wars: Andor",
      overview:
        "The tale of the burgeoning rebellion against the Empire and how people and planets became involved. In an era filled with danger, deception and intrigue, Cassian Andor embarks on the path that is destined to turn him into a rebel hero.",
      poster_path: "/59SVNwLfoMnZPPB6ukW6dlPxAdI.jpg",
      media_type: "tv",
      genre_ids: [10765, 10759, 10768],
      popularity: 497.75,
      first_air_date: "2022-09-21",
      vote_average: 8.153,
      vote_count: 363,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/wvIV32bGg6HC4dOCyXIHk9q4Lgt.jpg",
      id: 1042984,
      title: "Christmas Full of Grace",
      original_language: "pt",
      original_title: "Um Natal Cheio de Graça",
      overview:
        "After discovering a betrayal, Carlinhos takes a fun stranger to accompany him on Christmas. But Graça proves to be a madwoman capable of bringing the traditional family home down.",
      poster_path: "/iHRphB4zfPTuUHVrbO2vTmCLuHO.jpg",
      media_type: "movie",
      genre_ids: [10749, 35],
      popularity: 33.037,
      release_date: "2022-11-30",
      video: false,
      vote_average: 6.0,
      vote_count: 3,
    },
    {
      adult: false,
      backdrop_path: "/ugreOrjU6q6900nsICw4O9L4Cmr.jpg",
      id: 114410,
      name: "Chainsaw Man",
      original_language: "ja",
      original_name: "チェンソーマン",
      overview:
        "Denji has a simple dream—to live a happy and peaceful life, spending time with a girl he likes. This is a far cry from reality, however, as Denji is forced by the yakuza into killing devils in order to pay off his crushing debts. Using his pet devil Pochita as a weapon, he is ready to do anything for a bit of cash.",
      poster_path: "/npdB6eFzizki0WaZ1OvKcJrWe97.jpg",
      media_type: "tv",
      genre_ids: [16, 10759, 10765, 35],
      popularity: 1408.957,
      first_air_date: "2022-10-12",
      vote_average: 8.609,
      vote_count: 331,
      origin_country: ["JP"],
    },
    {
      adult: false,
      backdrop_path: "/79PcXPpbDWql74h8Y00mNwbYMbS.jpg",
      id: 664469,
      title: "Amsterdam",
      original_language: "en",
      original_title: "Amsterdam",
      overview:
        "In the 1930s, three friends—a doctor, a nurse, and an attorney—witness a murder, become suspects themselves and uncover one of the most outrageous plots in North American history.",
      poster_path: "/6sJcVzGCwrDCBMV0DU6eRzA2UxM.jpg",
      media_type: "movie",
      genre_ids: [80, 35, 36, 9648, 53],
      popularity: 137.176,
      release_date: "2022-09-27",
      video: false,
      vote_average: 6.1,
      vote_count: 387,
    },
    {
      adult: false,
      backdrop_path: "/7zQJYV02yehWrQN6NjKsBorqUUS.jpg",
      id: 724495,
      title: "The Woman King",
      original_language: "en",
      original_title: "The Woman King",
      overview:
        "The story of the Agojie, the all-female unit of warriors who protected the African Kingdom of Dahomey in the 1800s with skills and a fierceness unlike anything the world has ever seen, and General Nanisca as she trains the next generation of recruits and readies them for battle against an enemy determined to destroy their way of life.",
      poster_path: "/438QXt1E3WJWb3PqNniK0tAE5c1.jpg",
      media_type: "movie",
      genre_ids: [28, 18, 36],
      popularity: 3125.753,
      release_date: "2022-09-15",
      video: false,
      vote_average: 7.892,
      vote_count: 524,
    },
    {
      adult: false,
      backdrop_path: "/o3mothJXDR9vLlZHpwyfFCycCNx.jpg",
      id: 668461,
      title: "Slumberland",
      original_language: "en",
      original_title: "Slumberland",
      overview:
        "A young girl discovers a secret map to the dreamworld of Slumberland, and with the help of an eccentric outlaw, she traverses dreams and flees nightmares, with the hope that she will be able to see her late father again.",
      poster_path: "/f18kgonrgr8YvEuvshExS4XBGL8.jpg",
      media_type: "movie",
      genre_ids: [10751, 14, 12, 18],
      popularity: 1232.307,
      release_date: "2022-11-09",
      video: false,
      vote_average: 7.873,
      vote_count: 288,
    },
    {
      adult: false,
      backdrop_path: "/qtfMr08KQsWXnCHY0a96N8NpQ2l.jpg",
      id: 30984,
      name: "Bleach",
      original_language: "ja",
      original_name: "ブリーチ",
      overview:
        "For as long as he can remember, Ichigo Kurosaki has been able to see ghosts. But when he meets Rukia, a Soul Reaper who battles evil spirits known as Hollows, he finds his life is changed forever. Now, with a newfound wealth of spiritual energy, Ichigo discovers his true calling: to protect the living and the dead from evil.",
      poster_path: "/2EewmxXe72ogD0EaWM8gqa0ccIw.jpg",
      media_type: "tv",
      genre_ids: [10759, 16, 10765],
      popularity: 236.733,
      first_air_date: "2004-10-05",
      vote_average: 8.383,
      vote_count: 1371,
      origin_country: ["JP"],
    },
    {
      adult: false,
      backdrop_path: "/kP5k4gA6yJiQCeN5FNcGwRtGDuq.jpg",
      id: 736918,
      title: "The Noel Diary",
      original_language: "en",
      original_title: "The Noel Diary",
      overview:
        "Cleaning out his childhood home at Christmas, a novelist meets a woman searching for her birth mother. Will an old diary unlock their pasts — and hearts?",
      poster_path: "/j7bu4lMcGs7pjsAPQ3E4WOMFBNW.jpg",
      media_type: "movie",
      genre_ids: [10749, 35, 18],
      popularity: 280.102,
      release_date: "2022-11-24",
      video: false,
      vote_average: 6.674,
      vote_count: 86,
    },
    {
      adult: false,
      backdrop_path: "/6mEYUYdkKoVCMeYf3rTFj0L1uyv.jpg",
      id: 899112,
      title: "Violent Night",
      original_language: "en",
      original_title: "Violent Night",
      overview:
        "When a team of mercenaries breaks into a wealthy family compound on Christmas Eve, taking everyone inside hostage, the team isn’t prepared for a surprise combatant: Santa Claus is on the grounds, and he’s about to show why this Nick is no saint.",
      poster_path: "/nhXjUvOvq7rJlvJFCrZMUUJ9Mn0.jpg",
      media_type: "movie",
      genre_ids: [28, 35],
      popularity: 148.274,
      release_date: "2022-11-30",
      video: false,
      vote_average: 7.25,
      vote_count: 4,
    },
    {
      adult: false,
      backdrop_path: "/fHDvGGPFry65ou79WLi6JsjCZrM.jpg",
      id: 632856,
      title: "Spirited",
      original_language: "en",
      original_title: "Spirited",
      overview:
        "Each Christmas Eve, the Ghost of Christmas Present selects one dark soul to be reformed by a visit from three spirits. But this season, he picked the wrong Scrooge. Clint Briggs turns the tables on his ghostly host until Present finds himself reexamining his own past, present and future.",
      poster_path: "/h3zAzTMs5EP3cKusOxFNGSFE1WI.jpg",
      media_type: "movie",
      genre_ids: [35],
      popularity: 542.759,
      release_date: "2022-11-10",
      video: false,
      vote_average: 7.318,
      vote_count: 159,
    },
  ],
  total_pages: 1000,
  total_results: 20000,
};

export const movieData = {
  adult: false,
  backdrop_path: "/rfnmMYuZ6EKOBvQLp2wqP21v7sI.jpg",
  belongs_to_collection: null,
  budget: 0,
  genres: [
    { id: 35, name: "Comedy" },
    { id: 878, name: "Science Fiction" },
    { id: 12, name: "Adventure" },
  ],
  homepage:
    "https://www.disneyplus.com/movies/the-guardians-of-the-galaxy-holiday-special/5HUc4iuAVplq",
  id: 774752,
  imdb_id: "tt13623136",
  original_language: "en",
  original_title: "The Guardians of the Galaxy Holiday Special",
  overview:
    "On a mission to make Christmas unforgettable for Quill, the Guardians head to Earth in search of the perfect present.",
  popularity: 385.42,
  poster_path: "/8dqXyslZ2hv49Oiob9UjlGSHSTR.jpg",
  production_companies: [
    {
      id: 420,
      logo_path: "/hUzeosd33nzE5MCNsZxCGEKTXaQ.png",
      name: "Marvel Studios",
      origin_country: "US",
    },
    {
      id: 94218,
      logo_path: null,
      name: "Troll Court Entertainment",
      origin_country: "US",
    },
    {
      id: 176762,
      logo_path: null,
      name: "Kevin Feige Productions",
      origin_country: "US",
    },
  ],
  production_countries: [
    { iso_3166_1: "US", name: "United States of America" },
  ],
  release_date: "2022-11-25",
  revenue: 0,
  runtime: 45,
  spoken_languages: [
    { english_name: "English", iso_639_1: "en", name: "English" },
  ],
  status: "Released",
  tagline: "The perfect present is a galaxy away.",
  title: "The Guardians of the Galaxy Holiday Special",
  video: false,
  vote_average: 7.49,
  vote_count: 336,
};

export const airingTvToday = {
  page: 1,
  results: [
    {
      backdrop_path: "/rv5gu2gYbOEYoArzH7bqJuMxvBB.jpg",
      first_air_date: "2021-01-25",
      genre_ids: [18, 10751],
      id: 115646,
      name: "Lisa",
      origin_country: ["BE"],
      original_language: "nl",
      original_name: "Lisa",
      overview: "",
      popularity: 1582.545,
      poster_path: "/w2nOl7KhwcUj11YxEi9Nknj9cqu.jpg",
      vote_average: 6.4,
      vote_count: 33,
    },
    {
      backdrop_path: "/tjwXKgaoiS1tovSBNAxFYEpIQtO.jpg",
      first_air_date: "2020-10-05",
      genre_ids: [18, 10766, 10751],
      id: 111453,
      name: "Ghum Hai Kisi Ke Pyaar Mein",
      origin_country: ["IN"],
      original_language: "hi",
      original_name: "घुम है किसिकी प्यार में",
      overview:
        "Virat sacrifices his love to honour the promise he made to a dying man. Trapped between the past and the present, will he find love beyond the chains of duty?",
      popularity: 1512.68,
      poster_path: "/uNjnoT3RChs2r7O9pDyx7TNBvIj.jpg",
      vote_average: 5.9,
      vote_count: 7,
    },
    {
      backdrop_path: "/wR3jtz2StAwocO9ANKP7ELUfkcW.jpg",
      first_air_date: "2022-05-30",
      genre_ids: [18, 10751, 10766],
      id: 203887,
      name: "Banni Chow Home Delivery",
      origin_country: ["IN"],
      original_language: "hi",
      original_name: "Banni Chow Home Delivery",
      overview:
        "Self-sufficient Banni runs her meal delivery service. However, her life turns upside down when she is tasked with feeding a rich but emotionally unstable Yuvan.",
      popularity: 1412.311,
      poster_path: "/lc75BdFIIrdgDjmj3nX0BU1Uyot.jpg",
      vote_average: 0,
      vote_count: 0,
    },
    {
      backdrop_path: "/ugreOrjU6q6900nsICw4O9L4Cmr.jpg",
      first_air_date: "2022-10-12",
      genre_ids: [16, 10759, 10765, 35],
      id: 114410,
      name: "Chainsaw Man",
      origin_country: ["JP"],
      original_language: "ja",
      original_name: "チェンソーマン",
      overview:
        "Denji has a simple dream—to live a happy and peaceful life, spending time with a girl he likes. This is a far cry from reality, however, as Denji is forced by the yakuza into killing devils in order to pay off his crushing debts. Using his pet devil Pochita as a weapon, he is ready to do anything for a bit of cash.",
      popularity: 1408.957,
      poster_path: "/npdB6eFzizki0WaZ1OvKcJrWe97.jpg",
      vote_average: 8.6,
      vote_count: 327,
    },
    {
      backdrop_path: "/jANJGWIKavzyREXUMCHiXFzitDO.jpg",
      first_air_date: "2022-10-10",
      genre_ids: [10766, 18],
      id: 204370,
      name: "Travessia",
      origin_country: ["BR"],
      original_language: "pt",
      original_name: "Travessia",
      overview: "",
      popularity: 1392.048,
      poster_path: "/jFZJEoPzt2RKSsZG8QEWptX5Xyw.jpg",
      vote_average: 5,
      vote_count: 6,
    },
    {
      backdrop_path: null,
      first_air_date: "2019-01-28",
      genre_ids: [10763],
      id: 154300,
      name: "Euronews Hoy",
      origin_country: ["ES", "FR"],
      original_language: "es",
      original_name: "Euronews Hoy",
      overview: "",
      popularity: 1383.911,
      poster_path: "/ujeIjo0GTRbFJcgjhgFZda78A90.jpg",
      vote_average: 4.5,
      vote_count: 8,
    },
    {
      backdrop_path: "/1UCGE1Dl7iClKIbDMcGWiHKVWCU.jpg",
      first_air_date: "2022-05-30",
      genre_ids: [35, 10759, 10766],
      id: 197189,
      name: "Cara e Coragem",
      origin_country: ["BR"],
      original_language: "pt",
      original_name: "Cara e Coragem",
      overview: "",
      popularity: 1376.15,
      poster_path: "/8CXbCCGiJxi4AXPBQ1QPrehMIGG.jpg",
      vote_average: 5.7,
      vote_count: 33,
    },
    {
      backdrop_path: "/cl8NLaoztP877hTSYSy6YIUkChF.jpg",
      first_air_date: "2022-09-26",
      genre_ids: [10764],
      id: 210855,
      name: "Now what",
      origin_country: ["BE"],
      original_language: "nl",
      original_name: "Now what",
      overview:
        "7 young people co-house in Antwerp. They are all at the beginning of their adult life and have to decide what that should look like.",
      popularity: 1356.306,
      poster_path: "/89kiLK0S7Rbfjorvhm0vxTAgAH3.jpg",
      vote_average: 5.3,
      vote_count: 4,
    },
    {
      backdrop_path: "/1aQ0ETcIXFeC0uGcK7NvTg90zWi.jpg",
      first_air_date: "2022-08-22",
      genre_ids: [],
      id: 209326,
      name: "Rajjo",
      origin_country: ["IN"],
      original_language: "nl",
      original_name: "Rajjo",
      overview: "",
      popularity: 1328.025,
      poster_path: "/rdNwXdMDVDvjOlcXCPOR3m9t43r.jpg",
      vote_average: 0,
      vote_count: 0,
    },
    {
      backdrop_path: "/o8zk3QmHYMSC7UiJgFk81OFF1sc.jpg",
      first_air_date: "2022-08-22",
      genre_ids: [10766, 18],
      id: 204095,
      name: "Mar do Sertão",
      origin_country: ["BR"],
      original_language: "pt",
      original_name: "Mar do Sertão",
      overview: "",
      popularity: 1300.787,
      poster_path: "/ixgnqO8xhFMb1zr8RRFsyeZ9CdD.jpg",
      vote_average: 4.3,
      vote_count: 16,
    },
    {
      backdrop_path: "/9xWuVqoUfsYyPsHPeVIzAYds6in.jpg",
      first_air_date: "2022-09-05",
      genre_ids: [10764],
      id: 208711,
      name: "Een Jaar Van Je Leven",
      origin_country: ["NL"],
      original_language: "nl",
      original_name: "Een Jaar Van Je Leven",
      overview: "",
      popularity: 1299.298,
      poster_path: "/9Ws1h6Tu4cYs7rzeF06ZVmT0iux.jpg",
      vote_average: 5.3,
      vote_count: 4,
    },
    {
      backdrop_path: "/xfUnkXXSP2E2zssvI2Ux0PGn3Yu.jpg",
      first_air_date: "2022-10-03",
      genre_ids: [10763, 10767],
      id: 211660,
      name: "Cuomo",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Cuomo",
      overview:
        "A no-nonsense show featuring the day’s most important news from all perspectives.",
      popularity: 1295.137,
      poster_path: "/jg7nEqNlgkFQxkSNcLlVn66LXjk.jpg",
      vote_average: 2,
      vote_count: 6,
    },
    {
      backdrop_path: "/zJNEXWx3YyWGQioCbutFd5dcNYS.jpg",
      first_air_date: "2022-03-21",
      genre_ids: [10766, 10759, 10751],
      id: 157059,
      name: "Poliana Moça",
      origin_country: ["BR"],
      original_language: "pt",
      original_name: "Poliana Moça",
      overview: "",
      popularity: 1288.289,
      poster_path: "/17yQZnnodzS1ZrKcpqHnQV8eQGN.jpg",
      vote_average: 6.8,
      vote_count: 15,
    },
    {
      backdrop_path: "/5NboRtvAKCU0KJGs5rXbw9deQf.jpg",
      first_air_date: "2021-10-27",
      genre_ids: [],
      id: 197109,
      name: "¿Cómo se llama esta relación?",
      origin_country: ["US"],
      original_language: "en",
      original_name: "¿Cómo se llama esta relación?",
      overview:
        "The new stage of Yeh Rishta Kya Kehlata Hai will deal with the rivalry between sisters set within the premise of a love triangle. It will basically revolve around the story of two sisters, Akshara and Aarohi, and how they get entangled in a relationship with their love interest, Abhimanyu.",
      popularity: 1286.737,
      poster_path: "/6ZfiG4P7jivJV0wgcNMSiS2Owhh.jpg",
      vote_average: 0,
      vote_count: 0,
    },
    {
      backdrop_path: "/o5GsA1G5YEruuUNOYvWjlArIC37.jpg",
      first_air_date: "2022-09-19",
      genre_ids: [10766],
      id: 210506,
      name: "Sangue Oculto",
      origin_country: ["PT"],
      original_language: "pt",
      original_name: "Sangue Oculto",
      overview: "",
      popularity: 1259.312,
      poster_path: "/myCEG6C5Nk181jXzBek5MQEXpM2.jpg",
      vote_average: 2,
      vote_count: 1,
    },
    {
      backdrop_path: "/t2rAdgjSh0WYbXzdOB5zTDqzdCI.jpg",
      first_air_date: "2022-11-02",
      genre_ids: [18],
      id: 213713,
      name: "Faltu",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Faltu",
      overview:
        "What's in a name? Amidst the arid landscape of Rajasthan, a young woman with dreamy eyes struggles to prove her worth.",
      popularity: 1242.798,
      poster_path: "/sNaiDVJxPz0GrjEolEDgR5LUuK5.jpg",
      vote_average: 0,
      vote_count: 0,
    },
    {
      backdrop_path: "/3XjDhPzj7Myr8yzsTO8UB6E2oAu.jpg",
      first_air_date: "2011-02-28",
      genre_ids: [18, 80],
      id: 31586,
      name: "La Reina del Sur",
      origin_country: ["US"],
      original_language: "es",
      original_name: "La Reina del Sur",
      overview:
        "After years of blood, sweat and tears, a woman of humble origin ends up becoming a drug trafficking legend, with all that that means...",
      popularity: 907.661,
      poster_path: "/uBTlJDdPpRxYTfUnKw4wbuIGSEK.jpg",
      vote_average: 7.8,
      vote_count: 1448,
    },
    {
      backdrop_path: "/ry9SsBPOShH7eEL2dJc1coCBh8X.jpg",
      first_air_date: "2022-03-07",
      genre_ids: [35, 18],
      id: 157936,
      name: "For You",
      origin_country: ["PT"],
      original_language: "pt",
      original_name: "Por Ti",
      overview:
        "In the parish of Rio Meandro, two villages are at war over the construction of a dam that will submerge one of them: either Aldeia Velha or Aldeia Nova.",
      popularity: 861.372,
      poster_path: "/7GmlOYoR2GNiBRFs47azHIcqncR.jpg",
      vote_average: 4.9,
      vote_count: 11,
    },
    {
      backdrop_path: "/7ZBNbpkLhC2fS90j6onLS8qqfRX.jpg",
      first_air_date: "2004-10-25",
      genre_ids: [10764],
      id: 4682,
      name: "Strictly Come Dancing: It Takes Two",
      origin_country: ["GB"],
      original_language: "en",
      original_name: "Strictly Come Dancing: It Takes Two",
      overview:
        "The companion show to the popular BBC One programme Strictly Come Dancing which features interviews and training footage of the couples competing in the main Saturday night show, opinions from the judges on the previous Saturday show and the training footage for the next, and interviews with celebrities who have been watching the show.",
      popularity: 816.05,
      poster_path: "/1UOKLsJ3bopZHg6ntRfmO4C5Gcm.jpg",
      vote_average: 1,
      vote_count: 1,
    },
    {
      backdrop_path: "/tE6dWq9neq2IPSc6kJQdxyMrl7w.jpg",
      first_air_date: "2022-08-15",
      genre_ids: [10759, 10765, 18],
      id: 121750,
      name: "Darna",
      origin_country: ["PH"],
      original_language: "tl",
      original_name: "Darna",
      overview:
        "When fragments of a green crystal scatter in the city and turn people into destructive monsters, Narda embraces her destiny as Darna—the mighty protector of the powerful stone from Planet Marte.",
      popularity: 812.495,
      poster_path: "/CFOce6pbb3FRNaBaVdvNsCv5kR.jpg",
      vote_average: 4.8,
      vote_count: 12,
    },
  ],
  total_pages: 16,
  total_results: 317,
};

export const singleMovie = {
  adult: false,
  backdrop_path: "/rfnmMYuZ6EKOBvQLp2wqP21v7sI.jpg",
  belongs_to_collection: null,
  budget: 0,
  genres: [
    { id: 35, name: "Comedy" },
    { id: 878, name: "Science Fiction" },
    { id: 12, name: "Adventure" },
  ],
  homepage:
    "https://www.disneyplus.com/movies/the-guardians-of-the-galaxy-holiday-special/5HUc4iuAVplq",
  id: 774752,
  imdb_id: "tt13623136",
  original_language: "en",
  original_title: "The Guardians of the Galaxy Holiday Special",
  overview:
    "On a mission to make Christmas unforgettable for Quill, the Guardians head to Earth in search of the perfect present.",
  popularity: 539.588,
  poster_path: "/8dqXyslZ2hv49Oiob9UjlGSHSTR.jpg",
  production_companies: [
    {
      id: 420,
      logo_path: "/hUzeosd33nzE5MCNsZxCGEKTXaQ.png",
      name: "Marvel Studios",
      origin_country: "US",
    },
    {
      id: 94218,
      logo_path: null,
      name: "Troll Court Entertainment",
      origin_country: "US",
    },
    {
      id: 176762,
      logo_path: null,
      name: "Kevin Feige Productions",
      origin_country: "US",
    },
  ],
  production_countries: [
    { iso_3166_1: "US", name: "United States of America" },
  ],
  release_date: "2022-11-25",
  revenue: 0,
  runtime: 45,
  spoken_languages: [
    { english_name: "English", iso_639_1: "en", name: "English" },
  ],
  status: "Released",
  tagline: "The perfect present is a galaxy away.",
  title: "The Guardians of the Galaxy Holiday Special",
  video: false,
  vote_average: 7.527,
  vote_count: 391,
};

export const showData = {
  adult: false,
  backdrop_path: "/cl8NLaoztP877hTSYSy6YIUkChF.jpg",
  created_by: [],
  episode_run_time: [11],
  first_air_date: "2022-09-26",
  genres: [{ id: 10764, name: "Reality" }],
  homepage: "https://www.goplay.be/now-what",
  id: 210855,
  in_production: true,
  languages: ["nl"],
  last_air_date: "2022-11-30",
  last_episode_to_air: {
    air_date: "2022-11-30",
    episode_number: 66,
    id: 4013862,
    name: "Episode 66",
    overview: "",
    production_code: "",
    runtime: null,
    season_number: 1,
    show_id: 210855,
    still_path: null,
    vote_average: 0.0,
    vote_count: 0,
  },
  name: "Now what",
  next_episode_to_air: {
    air_date: "2022-12-01",
    episode_number: 67,
    id: 4013863,
    name: "Episode 67",
    overview: "",
    production_code: "",
    runtime: null,
    season_number: 1,
    show_id: 210855,
    still_path: null,
    vote_average: 0.0,
    vote_count: 0,
  },
  networks: [
    {
      id: 5708,
      name: "GoPlay",
      logo_path: "/kTehfjtP24Nx0qhJNODfo3h3nz5.png",
      origin_country: "BE",
    },
  ],
  number_of_episodes: 90,
  number_of_seasons: 1,
  origin_country: ["BE"],
  original_language: "nl",
  original_name: "Now what",
  overview:
    "7 young people co-house in Antwerp. They are all at the beginning of their adult life and have to decide what that should look like.",
  popularity: 1316.181,
  poster_path: "/89kiLK0S7Rbfjorvhm0vxTAgAH3.jpg",
  production_companies: [],
  production_countries: [{ iso_3166_1: "BE", name: "Belgium" }],
  seasons: [
    {
      air_date: "2022-09-26",
      episode_count: 90,
      id: 309846,
      name: "Season 1",
      overview: "",
      poster_path: null,
      season_number: 1,
    },
  ],
  spoken_languages: [
    { english_name: "Dutch", iso_639_1: "nl", name: "Nederlands" },
  ],
  status: "Returning Series",
  tagline: "",
  type: "Reality",
  vote_average: 5.2,
  vote_count: 4,
};

const movieCategories = {
  genres: [
    { id: 28, name: "Action" },
    { id: 12, name: "Adventure" },
    { id: 16, name: "Animation" },
    { id: 35, name: "Comedy" },
    { id: 80, name: "Crime" },
    { id: 99, name: "Documentary" },
    { id: 18, name: "Drama" },
    { id: 10751, name: "Family" },
    { id: 14, name: "Fantasy" },
    { id: 36, name: "History" },
    { id: 27, name: "Horror" },
    { id: 10402, name: "Music" },
    { id: 9648, name: "Mystery" },
    { id: 10749, name: "Romance" },
    { id: 878, name: "Science Fiction" },
    { id: 10770, name: "TV Movie" },
    { id: 53, name: "Thriller" },
    { id: 10752, name: "War" },
    { id: 37, name: "Western" },
  ],
};

const tvCategories = {
  genres: [
    { id: 10759, name: "Action & Adventure" },
    { id: 16, name: "Animation" },
    { id: 35, name: "Comedy" },
    { id: 80, name: "Crime" },
    { id: 99, name: "Documentary" },
    { id: 18, name: "Drama" },
    { id: 10751, name: "Family" },
    { id: 10762, name: "Kids" },
    { id: 9648, name: "Mystery" },
    { id: 10763, name: "News" },
    { id: 10764, name: "Reality" },
    { id: 10765, name: "Sci-Fi & Fantasy" },
    { id: 10766, name: "Soap" },
    { id: 10767, name: "Talk" },
    { id: 10768, name: "War & Politics" },
    { id: 37, name: "Western" },
  ],
};

const searchResults = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/bQXAqRx2Fgc46uCVWgoPz5L5Dtr.jpg",
      genre_ids: [28, 14, 878],
      id: 436270,
      media_type: "movie",
      original_language: "en",
      original_title: "Black Adam",
      overview:
        "Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.",
      popularity: 9137.939,
      poster_path: "/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg",
      release_date: "2022-10-19",
      title: "Black Adam",
      video: false,
      vote_average: 7.3,
      vote_count: 2296,
    },
    {
      adult: false,
      backdrop_path: "/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg",
      genre_ids: [28, 12, 878],
      id: 505642,
      media_type: "movie",
      original_language: "en",
      original_title: "Black Panther: Wakanda Forever",
      overview:
        "Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death. As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.",
      popularity: 1687.653,
      poster_path: "/ps2oKfhY6DL3alynlSqY97gHSsg.jpg",
      release_date: "2022-11-09",
      title: "Black Panther: Wakanda Forever",
      video: false,
      vote_average: 7.6,
      vote_count: 1129,
    },
    {
      adult: false,
      backdrop_path: "/b6ZJZHUdMEFECvGiDpJjlfUWela.jpg",
      genre_ids: [28, 12, 878],
      id: 284054,
      media_type: "movie",
      original_language: "en",
      original_title: "Black Panther",
      overview:
        "King T'Challa returns home to the reclusive, technologically advanced African nation of Wakanda to serve as his country's new leader. However, T'Challa soon finds that he is challenged for the throne by factions within his own country as well as without. Using powers reserved to Wakandan kings, T'Challa assumes the Black Panther mantle to join with ex-girlfriend Nakia, the queen-mother, his princess-kid sister, members of the Dora Milaje (the Wakandan 'special forces') and an American secret agent, to prevent Wakanda from being dragged into a world war.",
      popularity: 216.096,
      poster_path: "/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
      release_date: "2018-02-13",
      title: "Black Panther",
      video: false,
      vote_average: 7.4,
      vote_count: 19906,
    },
    {
      backdrop_path: "/czpfLUoJt7uPQf2i7S2Mo2cwRGl.jpg",
      first_air_date: "2014-09-24",
      genre_ids: [35],
      id: 61381,
      media_type: "tv",
      name: "black-ish",
      origin_country: ["US"],
      original_language: "en",
      original_name: "black-ish",
      overview:
        "A family man struggles to gain a sense of cultural identity while raising his kids in a predominantly white, upper-middle-class neighborhood.",
      popularity: 59.584,
      poster_path: "/ga1zJ6UejPIfyL8BA22pK6dqsC8.jpg",
      vote_average: 7.3,
      vote_count: 252,
    },
    {
      backdrop_path: "/q7XOgkp0NfjqVRYxzU0eGg7wSrm.jpg",
      first_air_date: "2011-12-04",
      genre_ids: [10765, 18, 9648],
      id: 42009,
      media_type: "tv",
      name: "Black Mirror",
      origin_country: ["GB"],
      original_language: "en",
      original_name: "Black Mirror",
      overview:
        "A contemporary British re-working of The Twilight Zone with stories that tap into the collective unease about our modern world. \n\nOver the last ten years, technology has transformed almost every aspect of our lives before we've had time to stop and question it. In every home; on every desk; in every palm - a plasma screen; a monitor; a smartphone - a black mirror of our 21st Century existence.",
      popularity: 82.626,
      poster_path: "/7PRddO7z7mcPi21nZTCMGShAyy1.jpg",
      vote_average: 8.3,
      vote_count: 3634,
    },
    {
      adult: false,
      backdrop_path: "/6FbWhRR5B7OWVgzXuTkIFiaI2N3.jpg",
      genre_ids: [28, 53],
      id: 848123,
      media_type: "movie",
      original_language: "fr",
      original_title: "Black Site",
      overview:
        "A group of officers based in a labyrinthine top-secret prison must fight for their lives against Hatchet, a brilliant and infamous high-value detainee. When he escapes, his mysterious and deadly agenda has far reaching and dire consequences.",
      popularity: 136.002,
      poster_path: "/ipn8khVVC4eToWiGf89WF9J5PJn.jpg",
      release_date: "2022-05-05",
      title: "Black Site",
      video: false,
      vote_average: 6.9,
      vote_count: 142,
    },
    {
      backdrop_path: "/9Sz85jzgFAt2NUWV6e9AfJUSRkM.jpg",
      first_air_date: "2006-04-09",
      genre_ids: [10759, 16, 18, 80],
      id: 12598,
      media_type: "tv",
      name: "Black Lagoon",
      origin_country: ["JP"],
      original_language: "ja",
      original_name: "BLACK LAGOON",
      overview:
        "The story follows a team of pirate mercenaries known as the Lagoon Company, that smuggles goods in and around the seas of Southeast Asia in the early to mid 1990s. Their base of operations is located in the fictional harbor city of Roanapur in southeast Thailand near the border of Cambodia.",
      popularity: 43.744,
      poster_path: "/PTmMkCIMZ8m0Dc1FtEkVRZ12r3.jpg",
      vote_average: 8,
      vote_count: 284,
    },
    {
      backdrop_path: "/mBHcWrRAtkRo9YgcHm1cUdLuyQ8.jpg",
      first_air_date: "2014-01-25",
      genre_ids: [18, 10759],
      id: 47665,
      media_type: "tv",
      name: "Black Sails",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Black Sails",
      overview:
        "The pirate adventures of Captain Flint and his men twenty years prior to Robert Louis Stevenson’s classic “Treasure Island.” Flint, the most brilliant and most feared pirate captain of his day, takes on a fast-talking young addition to his crew who goes by the name John Silver. Threatened with extinction on all sides, they fight for the survival of New Providence Island, the most notorious criminal haven of its day – a debauched paradise teeming with pirates, prostitutes, thieves and fortune seekers, a place defined by both its enlightened ideals and its stunning brutality.",
      popularity: 55.746,
      poster_path: "/mZcSwrDdw6cdOVgXm496DgwrQcQ.jpg",
      vote_average: 7.6,
      vote_count: 1079,
    },
    {
      adult: false,
      backdrop_path: "/AfvIjhDu9p64jKcmohS4hsPG95Q.jpg",
      genre_ids: [27, 53],
      id: 756999,
      media_type: "movie",
      original_language: "en",
      original_title: "The Black Phone",
      overview:
        "Finney Blake, a shy but clever 13-year-old boy, is abducted by a sadistic killer and trapped in a soundproof basement where screaming is of little use. When a disconnected phone on the wall begins to ring, Finney discovers that he can hear the voices of the killer’s previous victims. And they are dead set on making sure that what happened to them doesn’t happen to Finney.",
      popularity: 193.753,
      poster_path: "/lr11mCT85T1JanlgjMuhs9nMht4.jpg",
      release_date: "2022-06-22",
      title: "The Black Phone",
      video: false,
      vote_average: 7.8,
      vote_count: 3157,
    },
    {
      backdrop_path: "/aZ4mBxYHrKHFu9QpUmpVDIOoWAb.jpg",
      first_air_date: "2022-07-07",
      genre_ids: [18, 80],
      id: 155537,
      media_type: "tv",
      name: "Black Bird",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Black Bird",
      overview:
        "As Jimmy Keene begins a 10-year prison sentence, he gets an incredible offer: If he can elicit a confession from suspected killer Larry Hall, Jimmy will be freed. Completing this mission becomes the challenge of a lifetime.",
      popularity: 69.238,
      poster_path: "/ok7CID2LJ53j9Fc8VSPsfFxQk6Y.jpg",
      vote_average: 8.2,
      vote_count: 225,
    },
    {
      adult: false,
      backdrop_path: "/keIxh0wPr2Ymj0Btjh4gW7JJ89e.jpg",
      genre_ids: [28, 12, 878],
      id: 497698,
      media_type: "movie",
      original_language: "en",
      original_title: "Black Widow",
      overview:
        "Natasha Romanoff, also known as Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger.",
      popularity: 93.15,
      poster_path: "/ytnhzdwtj0YfC5NVWrrPRGSGZb7.jpg",
      release_date: "2021-07-07",
      title: "Black Widow",
      video: false,
      vote_average: 7.4,
      vote_count: 8375,
    },
    {
      backdrop_path: "/2YCv1rIWIy63dJsC4y8BjoI4l8L.jpg",
      first_air_date: "2013-03-30",
      genre_ids: [18, 10765],
      id: 56296,
      media_type: "tv",
      name: "Orphan Black",
      origin_country: ["US", "CA"],
      original_language: "en",
      original_name: "Orphan Black",
      overview:
        "A streetwise hustler is pulled into a compelling conspiracy after witnessing the suicide of a girl who looks just like her.",
      popularity: 46.147,
      poster_path: "/5sfJOpwnkuXmXK7K1YDcRY4rTE.jpg",
      vote_average: 7.8,
      vote_count: 1019,
    },
    {
      backdrop_path: "/kv0vCJOoGyWQdDPK9vFnyvqqDHt.jpg",
      first_air_date: "2018-01-16",
      genre_ids: [10759, 10765, 18],
      id: 71663,
      media_type: "tv",
      name: "Black Lightning",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Black Lightning",
      overview:
        "Jefferson Pierce is a man wrestling with a secret. As the father of two daughters and principal of a charter high school that also serves as a safe haven for young people in a New Orleans neighborhood overrun by gang violence, he is a hero to his community.",
      popularity: 48.965,
      poster_path: "/h1xbvvO6oqchfLe6xh0yLNnQxeM.jpg",
      vote_average: 7.2,
      vote_count: 735,
    },
    {
      adult: false,
      backdrop_path: "/jVsbzy5gj3McD8V6dDr7EMrLSqT.jpg",
      genre_ids: [99],
      id: 1040330,
      media_type: "movie",
      original_language: "en",
      original_title: "Black Adam: Saviour or Destroyer?",
      overview:
        "Ahead of the release of upcoming fantasy film ‘Black Adam’, sit down with Dwayne Johnson as he discusses his starring role as the eponymous superhero.",
      popularity: 179.545,
      poster_path: "/sTuXDWacwdcMS7NNLaynkfVBZkr.jpg",
      release_date: "2022-10-15",
      title: "Black Adam: Saviour or Destroyer?",
      video: false,
      vote_average: 7.1,
      vote_count: 252,
    },
    {
      backdrop_path: "/hRwyiBwWKbol9tg3fLFNFkuATqL.jpg",
      first_air_date: "2019-04-11",
      genre_ids: [10765, 18, 10759],
      id: 88052,
      media_type: "tv",
      name: "Black Summer",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Black Summer",
      overview:
        "In the dark, early days of a zombie apocalypse, complete strangers band together to find the strength they need to survive and get back to loved ones.",
      popularity: 41.827,
      poster_path: "/d27fZpY8jSZDOs1k0JCL0RY0b94.jpg",
      vote_average: 7.1,
      vote_count: 380,
    },
    {
      adult: false,
      gender: 2,
      id: 70851,
      known_for: [
        {
          adult: false,
          backdrop_path: "/vndouqEyQqpvvk0FwIlkfceblrh.jpg",
          genre_ids: [28, 12, 16, 10751, 35],
          id: 9502,
          media_type: "movie",
          original_language: "en",
          original_title: "Kung Fu Panda",
          overview:
            "When the Valley of Peace is threatened, lazy Po the panda discovers his destiny as the \"chosen one\" and trains to become a kung fu hero, but transforming the unsleek slacker into a brave warrior won't be easy. It's up to Master Shifu and the Furious Five -- Tigress, Crane, Mantis, Viper and Monkey -- to give it a try.",
          poster_path: "/xCn3VOST64XpOA8x0gaQkQiZtZY.jpg",
          release_date: "2008-06-04",
          title: "Kung Fu Panda",
          video: false,
          vote_average: 7.2,
          vote_count: 9768,
        },
        {
          adult: false,
          backdrop_path: "/7BdxZXbSkUiVeCRXKD3hi9KYeWm.jpg",
          genre_ids: [16, 10751],
          id: 49444,
          media_type: "movie",
          original_language: "en",
          original_title: "Kung Fu Panda 2",
          overview:
            "Po is now living his dream as The Dragon Warrior, protecting the Valley of Peace alongside his friends and fellow kung fu masters, The Furious Five - Tigress, Crane, Mantis, Viper and Monkey. But Po’s new life of awesomeness is threatened by the emergence of a formidable villain, who plans to use a secret, unstoppable weapon to conquer China and destroy kung fu. It is up to Po and The Furious Five to journey across China to face this threat and vanquish it. But how can Po stop a weapon that can stop kung fu? He must look to his past and uncover the secrets of his mysterious origins; only then will he be able to unlock the strength he needs to succeed.",
          poster_path: "/mtqqD00vB4PGRt20gWtGqFhrkd0.jpg",
          release_date: "2011-05-25",
          title: "Kung Fu Panda 2",
          video: false,
          vote_average: 6.9,
          vote_count: 5869,
        },
        {
          adult: false,
          backdrop_path: "/uT5G4fA7jKxlJNfwYPMm353f5AI.jpg",
          genre_ids: [28, 12, 16, 35, 10751],
          id: 140300,
          media_type: "movie",
          original_language: "en",
          original_title: "Kung Fu Panda 3",
          overview:
            'Continuing his "legendary adventures of awesomeness", Po must face two hugely epic, but different threats: one supernatural and the other a little closer to his home.',
          poster_path: "/pKrwkydrXKDX9rpMdzwqFQQLRfI.jpg",
          release_date: "2016-01-23",
          title: "Kung Fu Panda 3",
          video: false,
          vote_average: 6.9,
          vote_count: 4910,
        },
      ],
      known_for_department: "Acting",
      media_type: "person",
      name: "Jack Black",
      popularity: 39.997,
      profile_path: "/rtCx0fiYxJVhzXXdwZE2XRTfIKE.jpg",
    },
    {
      backdrop_path: "/AekZz93QCISOYFELhxyRCSzcAit.jpg",
      first_air_date: "2015-09-30",
      genre_ids: [18],
      id: 63418,
      media_type: "tv",
      name: "Code Black",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Code Black",
      overview:
        "Inspired by the award-winning documentary, this medical drama is set in the busiest and most notorious ER in the nation where the extraordinary staff confront a challenged system in order to protect their ideals and the patients who need them the most.",
      popularity: 27.837,
      poster_path: "/xUpISrmAGP4ZglmluNI8a0ENXyS.jpg",
      vote_average: 7.8,
      vote_count: 225,
    },
    {
      backdrop_path: "/sjd4JTiJt4wGi98DwnTyK8Vo4DD.jpg",
      first_air_date: "2013-07-11",
      genre_ids: [35, 18],
      id: 1424,
      media_type: "tv",
      name: "Orange Is the New Black",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Orange Is the New Black",
      overview:
        "A crime she committed in her youthful past sends Piper Chapman to a women's prison, where she trades her comfortable New York life for one of unexpected camaraderie and conflict in an eccentric group of fellow inmates.",
      popularity: 90.404,
      poster_path: "/ekaa7YjGPTkFLcPhwWXTnARuCEU.jpg",
      vote_average: 7.7,
      vote_count: 2024,
    },
    {
      backdrop_path: "/o56X5GUWgzkGJ90QDWn6NNkGEN7.jpg",
      first_air_date: "2021-03-04",
      genre_ids: [10765, 16, 10759],
      id: 112162,
      media_type: "tv",
      name: "Pacific Rim: The Black",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Pacific Rim: The Black",
      overview:
        "Two siblings - an idealistic teenage boy and his naïve younger sister - are forced to pilot an abandoned Jaeger across a hostile landscape in a desperate attempt to find their missing parents.",
      popularity: 41.494,
      poster_path: "/zZyKvdT5oukcWZbcEp2G6ZlVu58.jpg",
      vote_average: 8.3,
      vote_count: 359,
    },
    {
      adult: false,
      backdrop_path: "/fRrpOILyXuWaWLmqF7kXeMVwITQ.jpg",
      genre_ids: [27, 28, 12],
      id: 522444,
      media_type: "movie",
      original_language: "en",
      original_title: "Black Water: Abyss",
      overview:
        "An adventure-loving couple convince their friends to explore a remote, uncharted cave system in the forests of Northern Australia. With a tropical storm approaching, they abseil into the mouth of the cave, but when the caves start to flood, tensions rise as oxygen levels fall and the friends find themselves trapped. Unknown to them, the storm has also brought in a pack of dangerous and hungry crocodiles.",
      popularity: 41.798,
      poster_path: "/pmAv14TPE2vKMIRrVeCd1Ll7K94.jpg",
      release_date: "2020-07-09",
      title: "Black Water: Abyss",
      video: false,
      vote_average: 5.1,
      vote_count: 358,
    },
  ],
  total_pages: 343,
  total_results: 6849,
};
