export const data = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/rfnmMYuZ6EKOBvQLp2wqP21v7sI.jpg",
      id: 774752,
      title: "The Guardians of the Galaxy Holiday Special",
      original_language: "en",
      original_title: "The Guardians of the Galaxy Holiday Special",
      overview:
        "On a mission to make Christmas unforgettable for Quill, the Guardians head to Earth in search of the perfect present.",
      poster_path: "/8dqXyslZ2hv49Oiob9UjlGSHSTR.jpg",
      media_type: "movie",
      genre_ids: [35, 878, 12],
      popularity: 539.588,
      release_date: "2022-11-25",
      video: false,
      vote_average: 7.527,
      vote_count: 391,
    },
    {
      adult: false,
      backdrop_path: "/9DpB6wC1iY5jxLz91RT8tIIsXaf.jpg",
      id: 119051,
      name: "Wednesday",
      original_language: "en",
      original_name: "Wednesday",
      overview:
        "Wednesday Addams is sent to Nevermore Academy, a bizarre boarding school where she attempts to master her psychic powers, stop a monstrous killing spree of the town citizens, and solve the supernatural mystery that affected her family 25 years ago — all while navigating her new relationships.",
      poster_path: "/jeGtaMwGxPmQN5xM4ClnwPQcNQz.jpg",
      media_type: "tv",
      genre_ids: [10765, 9648, 35],
      popularity: 1956.231,
      first_air_date: "2022-11-23",
      vote_average: 8.802,
      vote_count: 969,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/93SxdkiR3gBcbG5FxIt0DCBttul.jpg",
      id: 111837,
      name: "Willow",
      original_language: "en",
      original_name: "Willow",
      overview:
        "Many years after the events of the original film, legendary sorcerer Willow leads a group of misfit heroes on a dangerous rescue mission through a world beyond their wildest imaginations.",
      poster_path: "/jhdSPDlhswjN1r6O0pGP3ZvQgU8.jpg",
      media_type: "tv",
      genre_ids: [10765, 10759, 18],
      popularity: 72.701,
      first_air_date: "2022-11-30",
      vote_average: 7.4,
      vote_count: 8,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/bQXAqRx2Fgc46uCVWgoPz5L5Dtr.jpg",
      id: 436270,
      title: "Black Adam",
      original_language: "en",
      original_title: "Black Adam",
      overview:
        "Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.",
      poster_path: "/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg",
      media_type: "movie",
      genre_ids: [28, 14, 878],
      popularity: 13251.998,
      release_date: "2022-10-19",
      video: false,
      vote_average: 7.284,
      vote_count: 2169,
    },
    {
      adult: false,
      backdrop_path: "/pHCLEj9i1R929p8feiwyq2arSgi.jpg",
      id: 873126,
      title: "My Name Is Vendetta",
      original_language: "it",
      original_title: "Il mio nome è vendetta",
      overview:
        "After old enemies kill his family, a former mafia enforcer and his feisty daughter flee to Milan, where they hide out while plotting their revenge.",
      poster_path: "/2cHGGU1CAhECNx6YY3oEbo6ysYb.jpg",
      media_type: "movie",
      genre_ids: [28, 12, 80, 9648, 53],
      popularity: 26.513,
      release_date: "2022-11-30",
      video: false,
      vote_average: 6.0,
      vote_count: 3,
    },
    {
      adult: false,
      backdrop_path: "/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg",
      id: 505642,
      title: "Black Panther: Wakanda Forever",
      original_language: "en",
      original_title: "Black Panther: Wakanda Forever",
      overview:
        "Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death. As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.",
      poster_path: "/ps2oKfhY6DL3alynlSqY97gHSsg.jpg",
      media_type: "movie",
      genre_ids: [28, 12, 878],
      popularity: 1960.335,
      release_date: "2022-11-09",
      video: false,
      vote_average: 7.5,
      vote_count: 1093,
    },
    {
      adult: false,
      backdrop_path: "/kumeuomlQwwi8RPTFUXjVoit91o.jpg",
      id: 945897,
      title: "A Man of Action",
      original_language: "es",
      original_title: "Un hombre de acción",
      overview:
        "Loosely inspired by the life of Lucio Urtubia, explore the figure of the so-called anarchist 'Robin Hood,' who ran a legendary counterfeiting operation in Paris that put him in the crosshairs of America's largest bank, when he managed to obtain a huge amount of money by forging traveler's checks to invest in causes he believed in.",
      poster_path: "/2sZAwJI7hPIXwQKp95RFXhCm619.jpg",
      media_type: "movie",
      genre_ids: [18, 36],
      popularity: 26.417,
      release_date: "2022-11-30",
      video: false,
      vote_average: 7.7,
      vote_count: 3,
    },
    {
      adult: false,
      backdrop_path: "/c1bz69r0v065TGFA5nqBiKzPDys.jpg",
      id: 830784,
      title: "Lyle, Lyle, Crocodile",
      original_language: "en",
      original_title: "Lyle, Lyle, Crocodile",
      overview:
        "When the Primm family moves to New York City, their young son Josh struggles to adapt to his new school and new friends. All of that changes when he discovers Lyle — a singing crocodile who loves baths, caviar and great music — living in the attic of his new home. But when Lyle’s existence is threatened by evil neighbor Mr. Grumps, the Primms must band together to show the world that family can come from the most unexpected places.",
      poster_path: "/irIS5Tn3TXjNi1R9BpWvGAN4CZ1.jpg",
      media_type: "movie",
      genre_ids: [35, 10751, 10402],
      popularity: 2159.911,
      release_date: "2022-10-07",
      video: false,
      vote_average: 7.71,
      vote_count: 88,
    },
    {
      adult: false,
      backdrop_path: "/198vrF8k7mfQ4FjDJsBmdQcaiyq.jpg",
      id: 76600,
      title: "Avatar: The Way of Water",
      original_language: "en",
      original_title: "Avatar: The Way of Water",
      overview:
        "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
      poster_path: "/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
      media_type: "movie",
      genre_ids: [878, 28, 12],
      popularity: 622.981,
      release_date: "2022-12-14",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/s1xnjbOIQtwGObPnydTebp74G2c.jpg",
      id: 90669,
      name: "1899",
      original_language: "zh",
      original_name: "1899",
      overview:
        "Passengers on an immigrant ship traveling to the new continent get caught in a mysterious riddle when they find a second vessel adrift on the open sea.",
      poster_path: "/8KGvYHQNOamON6ufQGjyhkiVn1V.jpg",
      media_type: "tv",
      genre_ids: [9648, 18],
      popularity: 2067.956,
      first_air_date: "2022-11-17",
      vote_average: 7.914,
      vote_count: 349,
      origin_country: ["DE"],
    },
    {
      adult: false,
      backdrop_path: "/ajztm40qDPqMONaSJhQ2PaNe2Xd.jpg",
      id: 83867,
      name: "Star Wars: Andor",
      original_language: "en",
      original_name: "Star Wars: Andor",
      overview:
        "The tale of the burgeoning rebellion against the Empire and how people and planets became involved. In an era filled with danger, deception and intrigue, Cassian Andor embarks on the path that is destined to turn him into a rebel hero.",
      poster_path: "/59SVNwLfoMnZPPB6ukW6dlPxAdI.jpg",
      media_type: "tv",
      genre_ids: [10765, 10759, 10768],
      popularity: 497.75,
      first_air_date: "2022-09-21",
      vote_average: 8.153,
      vote_count: 363,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/wvIV32bGg6HC4dOCyXIHk9q4Lgt.jpg",
      id: 1042984,
      title: "Christmas Full of Grace",
      original_language: "pt",
      original_title: "Um Natal Cheio de Graça",
      overview:
        "After discovering a betrayal, Carlinhos takes a fun stranger to accompany him on Christmas. But Graça proves to be a madwoman capable of bringing the traditional family home down.",
      poster_path: "/iHRphB4zfPTuUHVrbO2vTmCLuHO.jpg",
      media_type: "movie",
      genre_ids: [10749, 35],
      popularity: 33.037,
      release_date: "2022-11-30",
      video: false,
      vote_average: 6.0,
      vote_count: 3,
    },
    {
      adult: false,
      backdrop_path: "/ugreOrjU6q6900nsICw4O9L4Cmr.jpg",
      id: 114410,
      name: "Chainsaw Man",
      original_language: "ja",
      original_name: "チェンソーマン",
      overview:
        "Denji has a simple dream—to live a happy and peaceful life, spending time with a girl he likes. This is a far cry from reality, however, as Denji is forced by the yakuza into killing devils in order to pay off his crushing debts. Using his pet devil Pochita as a weapon, he is ready to do anything for a bit of cash.",
      poster_path: "/npdB6eFzizki0WaZ1OvKcJrWe97.jpg",
      media_type: "tv",
      genre_ids: [16, 10759, 10765, 35],
      popularity: 1408.957,
      first_air_date: "2022-10-12",
      vote_average: 8.609,
      vote_count: 331,
      origin_country: ["JP"],
    },
    {
      adult: false,
      backdrop_path: "/79PcXPpbDWql74h8Y00mNwbYMbS.jpg",
      id: 664469,
      title: "Amsterdam",
      original_language: "en",
      original_title: "Amsterdam",
      overview:
        "In the 1930s, three friends—a doctor, a nurse, and an attorney—witness a murder, become suspects themselves and uncover one of the most outrageous plots in North American history.",
      poster_path: "/6sJcVzGCwrDCBMV0DU6eRzA2UxM.jpg",
      media_type: "movie",
      genre_ids: [80, 35, 36, 9648, 53],
      popularity: 137.176,
      release_date: "2022-09-27",
      video: false,
      vote_average: 6.1,
      vote_count: 387,
    },
    {
      adult: false,
      backdrop_path: "/7zQJYV02yehWrQN6NjKsBorqUUS.jpg",
      id: 724495,
      title: "The Woman King",
      original_language: "en",
      original_title: "The Woman King",
      overview:
        "The story of the Agojie, the all-female unit of warriors who protected the African Kingdom of Dahomey in the 1800s with skills and a fierceness unlike anything the world has ever seen, and General Nanisca as she trains the next generation of recruits and readies them for battle against an enemy determined to destroy their way of life.",
      poster_path: "/438QXt1E3WJWb3PqNniK0tAE5c1.jpg",
      media_type: "movie",
      genre_ids: [28, 18, 36],
      popularity: 3125.753,
      release_date: "2022-09-15",
      video: false,
      vote_average: 7.892,
      vote_count: 524,
    },
    {
      adult: false,
      backdrop_path: "/o3mothJXDR9vLlZHpwyfFCycCNx.jpg",
      id: 668461,
      title: "Slumberland",
      original_language: "en",
      original_title: "Slumberland",
      overview:
        "A young girl discovers a secret map to the dreamworld of Slumberland, and with the help of an eccentric outlaw, she traverses dreams and flees nightmares, with the hope that she will be able to see her late father again.",
      poster_path: "/f18kgonrgr8YvEuvshExS4XBGL8.jpg",
      media_type: "movie",
      genre_ids: [10751, 14, 12, 18],
      popularity: 1232.307,
      release_date: "2022-11-09",
      video: false,
      vote_average: 7.873,
      vote_count: 288,
    },
    {
      adult: false,
      backdrop_path: "/qtfMr08KQsWXnCHY0a96N8NpQ2l.jpg",
      id: 30984,
      name: "Bleach",
      original_language: "ja",
      original_name: "ブリーチ",
      overview:
        "For as long as he can remember, Ichigo Kurosaki has been able to see ghosts. But when he meets Rukia, a Soul Reaper who battles evil spirits known as Hollows, he finds his life is changed forever. Now, with a newfound wealth of spiritual energy, Ichigo discovers his true calling: to protect the living and the dead from evil.",
      poster_path: "/2EewmxXe72ogD0EaWM8gqa0ccIw.jpg",
      media_type: "tv",
      genre_ids: [10759, 16, 10765],
      popularity: 236.733,
      first_air_date: "2004-10-05",
      vote_average: 8.383,
      vote_count: 1371,
      origin_country: ["JP"],
    },
    {
      adult: false,
      backdrop_path: "/kP5k4gA6yJiQCeN5FNcGwRtGDuq.jpg",
      id: 736918,
      title: "The Noel Diary",
      original_language: "en",
      original_title: "The Noel Diary",
      overview:
        "Cleaning out his childhood home at Christmas, a novelist meets a woman searching for her birth mother. Will an old diary unlock their pasts — and hearts?",
      poster_path: "/j7bu4lMcGs7pjsAPQ3E4WOMFBNW.jpg",
      media_type: "movie",
      genre_ids: [10749, 35, 18],
      popularity: 280.102,
      release_date: "2022-11-24",
      video: false,
      vote_average: 6.674,
      vote_count: 86,
    },
    {
      adult: false,
      backdrop_path: "/6mEYUYdkKoVCMeYf3rTFj0L1uyv.jpg",
      id: 899112,
      title: "Violent Night",
      original_language: "en",
      original_title: "Violent Night",
      overview:
        "When a team of mercenaries breaks into a wealthy family compound on Christmas Eve, taking everyone inside hostage, the team isn’t prepared for a surprise combatant: Santa Claus is on the grounds, and he’s about to show why this Nick is no saint.",
      poster_path: "/nhXjUvOvq7rJlvJFCrZMUUJ9Mn0.jpg",
      media_type: "movie",
      genre_ids: [28, 35],
      popularity: 148.274,
      release_date: "2022-11-30",
      video: false,
      vote_average: 7.25,
      vote_count: 4,
    },
    {
      adult: false,
      backdrop_path: "/fHDvGGPFry65ou79WLi6JsjCZrM.jpg",
      id: 632856,
      title: "Spirited",
      original_language: "en",
      original_title: "Spirited",
      overview:
        "Each Christmas Eve, the Ghost of Christmas Present selects one dark soul to be reformed by a visit from three spirits. But this season, he picked the wrong Scrooge. Clint Briggs turns the tables on his ghostly host until Present finds himself reexamining his own past, present and future.",
      poster_path: "/h3zAzTMs5EP3cKusOxFNGSFE1WI.jpg",
      media_type: "movie",
      genre_ids: [35],
      popularity: 542.759,
      release_date: "2022-11-10",
      video: false,
      vote_average: 7.318,
      vote_count: 159,
    },
  ],
  total_pages: 1000,
  total_results: 20000,
};

export const movieData = {
  adult: false,
  backdrop_path: "/rfnmMYuZ6EKOBvQLp2wqP21v7sI.jpg",
  belongs_to_collection: null,
  budget: 0,
  genres: [
    { id: 35, name: "Comedy" },
    { id: 878, name: "Science Fiction" },
    { id: 12, name: "Adventure" },
  ],
  homepage:
    "https://www.disneyplus.com/movies/the-guardians-of-the-galaxy-holiday-special/5HUc4iuAVplq",
  id: 774752,
  imdb_id: "tt13623136",
  original_language: "en",
  original_title: "The Guardians of the Galaxy Holiday Special",
  overview:
    "On a mission to make Christmas unforgettable for Quill, the Guardians head to Earth in search of the perfect present.",
  popularity: 385.42,
  poster_path: "/8dqXyslZ2hv49Oiob9UjlGSHSTR.jpg",
  production_companies: [
    {
      id: 420,
      logo_path: "/hUzeosd33nzE5MCNsZxCGEKTXaQ.png",
      name: "Marvel Studios",
      origin_country: "US",
    },
    {
      id: 94218,
      logo_path: null,
      name: "Troll Court Entertainment",
      origin_country: "US",
    },
    {
      id: 176762,
      logo_path: null,
      name: "Kevin Feige Productions",
      origin_country: "US",
    },
  ],
  production_countries: [
    { iso_3166_1: "US", name: "United States of America" },
  ],
  release_date: "2022-11-25",
  revenue: 0,
  runtime: 45,
  spoken_languages: [
    { english_name: "English", iso_639_1: "en", name: "English" },
  ],
  status: "Released",
  tagline: "The perfect present is a galaxy away.",
  title: "The Guardians of the Galaxy Holiday Special",
  video: false,
  vote_average: 7.49,
  vote_count: 336,
};
